name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ["8", "12"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test